### ISSUE TITLE
OGPが上手く反映されない。

### ISSUE THREAD

**Issue by Yosh0124** [CreatorsLab/CorporatePage#21]
原因不明。要調査。

**Comment by Yosh0124** [comment]
デバッグ方法はここを参照。
https://creatorslab.qiita.com/Yosh0124/items/caeaa6110520afec97cb

**Comment by Yosh0124** [comment]
「このドメインはお名前ドットコム〜」という記述はなくなりましたが、やはり狙いの設定にできていない模様。iloliも同様でした。引き続き原因追求します。

**Comment by Yosh0124** [comment]
結局これ解決できてません。。。どなたか気づいたことあればご指摘下さい。

**Comment by yutakiyama** [comment]
とりあえず、潰せるものから潰していく…

**Comment by Yosh0124** [comment]
だね。。。俺も頑張って原因見つけます

**Comment by yutakiyama** [comment]
OGPの位置をできるだけ上部に表示＋全角スペースを削除したところ、なんとかFBから見てもらえた。

![2015-09-04 22 13 46](https://cloud.githubusercontent.com/assets/2705934/9684425/6fa63988-5352-11e5-984a-71cc539920ba.png)

けど、なんか文字化けしてる:sob:

**Comment by Yosh0124** [comment]
ほんまや。。。場所のタグも追加せなあかんのかな？

**Comment by Yosh0124** [comment]
いや、追加してるなぁ。
ドキュメントにのってない裏ルールがあるんかなぁ

**Comment by Yosh0124** [comment]
企業ページ大幅変更のため一旦クローズ
